<a href="https://colab.research.google.com/github/A-THAKUR22/AprilAssignments/blob/main/Assignment2April2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.

A company has gathered data on salaries, company names, job roles, and educational qualifications of employees. The dataset includes information about whether each employee's salary exceeds $100k (1) or not (0). Using this data, the company aims to build a decision tree classification model to predict whether a new employee, based on their company, job role, and degree, is likely to have a salary exceeding $100k.


2.

In this file using following columns build a model to predict if person would survive or not,PclassSexAgeFareCalculate score of your model

In [250]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [251]:
emp_data=pd.read_csv('salaries (2).csv')
emp_data

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [252]:
emp_data.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [253]:
encoder=LabelEncoder()
emp_data['Encoded_company']=encoder.fit_transform(emp_data['company'])
emp_data['Encoded_job']=encoder.fit_transform(emp_data['job'])
emp_data['Encoded_degree']=encoder.fit_transform(emp_data['degree'])

In [254]:
emp_data

,company,job,degree,salary_more_then_100k,Encoded_company,Encoded_job,Encoded_degree
0,google,sales executive,bachelors,0,2,2,0
1,google,sales executive,masters,0,2,2,1
2,google,business manager,bachelors,1,2,0,0
3,google,business manager,masters,1,2,0,1
4,google,computer programmer,bachelors,0,2,1,0
5,google,computer programmer,masters,1,2,1,1
6,abc pharma,sales executive,masters,0,0,2,1
7,abc pharma,computer programmer,bachelors,0,0,1,0
8,abc pharma,business manager,bachelors,0,0,0,0
9,abc pharma,business manager,masters,1,0,0,1
10,facebook,sales executive,bachelors,1,1,2,0
11,facebook,sales executive,masters,1,1,2,1
12,facebook,business manager,bachelors,1,1,0,0
13,facebook,business manager,masters,1,1,0,1
14,facebook,computer programmer,bachelors,1,1,1,0
15,facebook,computer programmer,masters,1,1,1,1

In [255]:
X=emp_data[['Encoded_company','Encoded_job','Encoded_degree']]
y=emp_data['salary_more_then_100k']

In [256]:
X

    Encoded_company  Encoded_job  Encoded_degree
0                 2            2               0
1                 2            2               1
2                 2            0               0
3                 2            0               1
4                 2            1               0
5                 2            1               1
6                 0            2               1
7                 0            1               0
8                 0            0               0
9                 0            0               1
10                1            2               0
11                1            2               1
12                1            0               0
13                1            0               1
14                1            1               0
15                1            1               1

In [257]:
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [336]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=42)
model=DecisionTreeClassifier(max_depth=3)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [337]:
y_predict=model.predict(X_test)
print(f'Predicions of the salary based on the given data are : {y_predict}')

Predicions of the salary based on the given data are : [0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1
 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0
 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1]

In [338]:
Accuracy=accuracy_score(y_test,y_predict)
print(f'Accuracy of our model is : {Accuracy}')

Accuracy of our model is : 0.8044871794871795

In [339]:
y_predict2=model.predict(X_train)
acc2=accuracy_score(y_train,y_predict2)
acc2

0.8169257340241797

In [262]:
titanic_data=pd.read_csv('titanic.csv')
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [263]:
titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [264]:
med_age = titanic_data['Age'].median()
titanic_data['Age'].fillna(med_age, inplace=True)
titanic_data = titanic_data.drop('Cabin', axis=1)
mode_embarked = titanic_data['Embarked'].mode()[0]
titanic_data['Embarked'].fillna(mode_embarked, inplace=True)
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [265]:
titanic_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [266]:
correlation=titanic_data.corr()['Survived'].drop('Survived')
correlation

<ipython-input-266-22ae814a91ea>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation=titanic_data.corr()['Survived'].drop('Survived')

PassengerId   -0.005007
Pclass        -0.338481
Age           -0.064910
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Name: Survived, dtype: float64

In [267]:
encoder = LabelEncoder()
titanic_data['encoded_sex'] = encoder.fit_transform(titanic_data['Sex'])
titanic_data['encoded_embarked'] = encoder.fit_transform(titanic_data['Embarked'])

In [268]:
correlation=titanic_data.corr()['Survived'].drop('Survived')
correlation

<ipython-input-268-22ae814a91ea>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation=titanic_data.corr()['Survived'].drop('Survived')

PassengerId        -0.005007
Pclass             -0.338481
Age                -0.064910
SibSp              -0.035322
Parch               0.081629
Fare                0.257307
encoded_sex        -0.543351
encoded_embarked   -0.167675
Name: Survived, dtype: float64

In [269]:
X=titanic_data[['Pclass','encoded_sex','Fare']]
y=titanic_data['Survived']

In [270]:
X

     Pclass  encoded_sex     Fare
0         3            1   7.2500
1         1            0  71.2833
2         3            0   7.9250
3         1            0  53.1000
4         3            1   8.0500
..      ...          ...      ...
886       2            1  13.0000
887       1            0  30.0000
888       3            0  23.4500
889       1            1  30.0000
890       3            1   7.7500

[891 rows x 3 columns]

In [271]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [384]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=DecisionTreeClassifier(max_depth=4)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=4)

In [385]:
y_pred=model.predict(X_test)
print(f'Predictions of people surviving or not: {y_pred}')

Predictions of people surviving or not: [0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1
 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1
 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 1 1]

In [386]:
Accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy of our model : {Accuracy}')

Accuracy of our model : 0.8044692737430168

In [387]:
y_pred2=model.predict(X_train)
acc2=accuracy_score(y_train,y_pred2)
acc2

0.8188202247191011